spring:
  application:
    name:eureka-server

server:
  port: 1111

eureka:
  instance:
    hostname:node1
  client:
    registerWithEureka: false  # Eureka Server同时也是Client，但没必要注册和获取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://node2:1112/eureka/
